rootProject.name = "crowdproj-comments"

include("comments-api-v1")
include("comments-common")
include("comments-mappers-v1")
include("comments-stubs")
include("comments-biz")
include("comments-app-ktor")
include("comments-swagger")
include("comments-app-common")
include("comments-lib-logging-common")
include("comments-lib-logging-oshai")
include("comments-api-log")
include("comments-mappers-log")
include("comments-lib-logging-logback")